language: clojure
jdk:
  - oraclejdk8
sudo: required
install: yes | sudo lein upgrade "2.7.1"
script: lein do clean, test, cljsbuild once, deploy
env:
  - LEIN_USERNAME=dtreskunov
  - secure: "rPeGreUcP1W8sa9vlvz78pP6DQ+NRf/snBD3xt1O1EVt0WR09mIt4P3ax3yVDLdik7s1bdjWf6BwQFwnRrMWmCMi4erhATtt4hWknUqUwOxi8mKioMYibCrGINcQ2oDJ13M4IaRbjEekrcx3Vt7pa5RobhCu2ZZm6mAfSxjoKupSh2V4BWKihfDKj7MH21CszpqLOOMcGi3L4ycDOowNrUWZcaRghHrr5yJt8eQUyqWXbpcpr6rjBpDOSYPyJWUX95kpfKH0iF2jNujij9vdG12lXfk+lOQ6TrwR7WDcghy2b0V/Q2rw0RfU4Ni8EO9q971zlti0zzejq+cFMkly2RZMyThHXeJgWruOUGIFGWbdI3kDTtITzUSvI4McnBdNxdG2AX5dv4q8mlDwa7ydxOThXAfWvMkuyZTN+CY7i6QkfuX6KBVMsD/eJ/yZB6ildwT+JjUT4cTMTVhPtxgFPO4mNoSgI0wEBIHqlbWuFP0S9MGujCJrTChyctXne66iUbz0/nFX2YhnjsGar226gHITj5CKQtjMT9xqjz23A0Mj/usBQlWI6V1Ef75uGYZQxdJnmwl1gwucfhfsS5ZQDhsEHuOpfsq+YVqSZVtb6yAkieexb5YJmxDkNYYEXI6ERRG33RmL4y8KskIcSRBJ93Uf64se+bqHH2gg1CRn23w="
